### ISSUE TITLE
gettimeofday

### ISSUE THREAD

**Issue by yegor256** [objectionary/eo-sys#5]
Let's make a test that calls [`gettimeofday`](https://man7.org/linux/man-pages/man2/gettimeofday.2.html)

**Comment by yegor256** [comment]
@mximp please, help or delegate

**Comment by mximp** [comment]
@yegor256 Do you suggest to call system function directly, bypassing JVM?
What is the purpose?

**Comment by yegor256** [comment]
@mximp the goal is to reduce the amount of atoms

**Comment by mximp** [comment]
@yegor256 do we have a bridge to call system functions from EO?

**Comment by yegor256** [comment]
@mximp yes, this repository provides this bridge :) see the README

**Comment by mximp** [comment]
[Work with native structures](https://stackoverflow.com/questions/73335655/getting-pointer-from-native-syscall-in-java)

**Comment by mximp** [comment]
@yegor256 this is done and can be closed

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.6`

**Comment by yegor256** [comment]
@mximp thanks!
