### ISSUE TITLE
one more release

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-sys#59]
We need to made a new release with this changes: https://github.com/objectionary/eo-sys/pull/54
This should help with this issue: https://github.com/objectionary/eo/issues/1898

**Comment by Graur** [comment]
@yegor256 Can you help, please? I suggest `0.0.9` version

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.9`

**Comment by Graur** [comment]
@yegor256 Thanks!
