### ISSUE TITLE
latest release tag is wrong

### ISSUE THREAD

**Issue by Graur** [objectionary/eo-sys#68]
When I'm trying to get the version of the latest release of this project by https://api.github.com/repos/objectionary/eo-sys/releases/latest I've faced the wrong version. Right now latest tag shows us `0.0.5`, but latest release version is `0.0.10`

**Comment by Graur** [comment]
All we need to do is to say to `rultor` to avoid pre-releases. Like here: https://github.com/yegor256/bibcop/blob/master/.rultor.yml#L14

**Comment by maxonfjvipon** [comment]
@Graur please check one more time and close the issue if there's nothing wrong

**Comment by Graur** [comment]
@maxonfjvipon Yep, it's good. Thanks!
