### ISSUE TITLE
Get rid of weak typed atoms in the repository

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eo-sys#71]
In order to prohibit using weak typed atoms (`/?`, see https://github.com/objectionary/eo/issues/1305) outside of `org.eolang` package we need to get rid of the weak typed atoms here

**Comment by 0pdd** [comment]
@maxonfjvipon the puzzle [#73](https://github.com/objectionary/eo-sys/issues/73) is still not solved.

**Comment by maxonfjvipon** [comment]
@yegor256 please release with tag `0.0.11`

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.11`

**Comment by yegor256** [comment]
@maxonfjvipon done
